### ISSUE TITLE
New Ui problems

### ISSUE THREAD

**Issue by rezasalimi01** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons#4]
Hi
It has some problem in new version of Jetbrains IDE
somtimes is okay
but most of times the plugin is not going to apply in New UI

**Comment by jonathanlermitage** [comment]
Hi! This is a duplicate of #2  
Sometimes it works, sometimes you have to restart (many times) the IDE. It seems to be a bug on the JetBrains side, I can do nothing for now 😅
