### ISSUE TITLE
red close icon for tabs

### ISSUE THREAD

**Issue by jstnfst** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons#5]
The red icon in the tab that indicates where you click to close the tab should instead be the same color as the text.

I find it distracting to have red X icons on every tab.

**Comment by jonathanlermitage** [comment]
The plugin is configurable. Go to Settings / Extra Toolwindow..., then uncheck the red close icons (there are 5 icons like that). Restart IDE. Enjoy 😎

**Comment by jstnfst** [comment]
oh! sick! thank you very much

**Comment by jonathanlermitage** [comment]
No problem 😀  
Maybe should I find a way to present the config panel, because many users simply ignore they can disable icons customization, and I can't blame them for that. But, for now, I have no idea...
