### ISSUE TITLE
Android Studio IDE - NEW UI icons not working

### ISSUE THREAD

**Issue by KarolCieslar** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons#7]
_**Android Studio Hedgehog | 2023.1.1 Patch 1
Build #AI-231.9392.1.2311.11255304, built on December 26, 2023**_

Any icons are not colored :(

**Comment by jonathanlermitage** [comment]
Android Studio is based on an outdated version of IntelliJ. This issue has been fixed in recent versions of IntelliJ (2023.3, if my memory is correct).  
Consider switching to Android Studio Canary, or wait for a future release.
